using System.Collections.Generic;
using System.IO;

namespace AInimator.Controller.Bundle
{
    /// <summary>
    /// Loads a controller bundle (<c>controller.onnx</c> + <c>norm_stats.json</c>
    /// + <c>manifest.json</c> + <c>presets/*.json</c>) from a directory on
    /// disk and validates it against the frozen I/O contract
    /// (apps/spec/inference_contract.md) before it is handed to
    /// <see cref="Runtime.ControllerRuntime"/>.
    /// </summary>
    /// <remarks>
    /// The bundle directory is a **build artifact**, never a versioned
    /// asset: it is (re)generated by the <c>apps/build/</c> orchestrator
    /// (ROADMAP_PLUGINS.md §3.4) and copied under
    /// <c>StreamingAssets/AInimatorBundle/</c> before the engine build. This
    /// loader only ever reads a plain directory path — it never assumes a
    /// specific delivery mechanism (StreamingAssets vs. an
    /// editor-time absolute path used by tests), which keeps it testable
    /// without Unity's asset pipeline.
    /// </remarks>
    public static class BundleLoader
    {
        public const string OnnxFileName = "controller.onnx";
        public const string ManifestFileName = "manifest.json";
        public const string NormStatsFileName = "norm_stats.json";
        public const string PresetsSubdirectory = "presets";

        /// <summary>
        /// The bundle-format version this plugin build was written against.
        /// Loaded bundles must share prefix + major with this value
        /// (see <see cref="BundleVersion.IsCompatibleWith"/>).
        /// </summary>
        public const string SupportedBundleVersion = "A7.0";

        /// <summary>
        /// Load and validate a controller bundle from <paramref name="bundleDirectory"/>.
        /// </summary>
        /// <param name="bundleDirectory">
        /// Absolute path to a directory containing <c>controller.onnx</c>,
        /// <c>manifest.json</c>, <c>norm_stats.json</c> and, optionally, a
        /// <c>presets/</c> subdirectory.
        /// </param>
        /// <exception cref="BundleLoadException">
        /// Thrown on any missing file, malformed JSON, or a manifest that
        /// fails contract validation — always loud, never silent
        /// (Goal B verite #4).
        /// </exception>
        public static ControllerBundle Load(string bundleDirectory)
        {
            if (string.IsNullOrEmpty(bundleDirectory) || !Directory.Exists(bundleDirectory))
            {
                throw new BundleLoadException(
                    $"Bundle directory not found: '{bundleDirectory}'. " +
                    "Did the build orchestrator (apps/build/) copy a fresh bundle " +
                    "into StreamingAssets before this build?");
            }

            var manifest = LoadManifest(bundleDirectory);
            ValidateManifest(manifest);

            var normStats = LoadNormStats(bundleDirectory);
            ValidateNormStats(manifest, normStats);

            var onnxBytes = LoadOnnxBytes(bundleDirectory);
            var presets = LoadPresets(bundleDirectory, manifest);

            return new ControllerBundle(manifest, normStats, onnxBytes, presets);
        }

        private static Manifest LoadManifest(string bundleDirectory)
        {
            var path = Path.Combine(bundleDirectory, ManifestFileName);
            if (!File.Exists(path))
            {
                throw new BundleLoadException($"Bundle is missing '{ManifestFileName}' at '{path}'.");
            }

            var json = File.ReadAllText(path);
            Manifest manifest;
            try
            {
                manifest = UnityEngine.JsonUtility.FromJson<Manifest>(json);
            }
            catch (System.Exception ex)
            {
                throw new BundleLoadException($"Failed to parse '{ManifestFileName}': {ex.Message}", ex);
            }

            if (manifest == null)
            {
                throw new BundleLoadException($"'{ManifestFileName}' parsed to null.");
            }

            return manifest;
        }

        /// <summary>
        /// Fail-fast contract validation (Goal B verite #4): reject a
        /// manifest whose version or frozen dims do not match what this
        /// plugin build expects.
        /// </summary>
        private static void ValidateManifest(Manifest manifest)
        {
            var loaded = BundleVersion.Parse(manifest.bundle_version);
            var supported = BundleVersion.Parse(SupportedBundleVersion);
            if (!loaded.IsCompatibleWith(supported))
            {
                throw new BundleLoadException(
                    $"Incompatible bundle_version '{manifest.bundle_version}': this plugin build " +
                    $"supports '{SupportedBundleVersion}' (same major). Regenerate the bundle with a " +
                    "matching ainimator export, or update the plugin.");
            }

            RequireEquals(manifest.state_channels, 136, nameof(manifest.state_channels));
            RequireEquals(manifest.num_bones, 22, nameof(manifest.num_bones));
            RequireEquals(manifest.rotation_channels_per_bone, 6, nameof(manifest.rotation_channels_per_bone));
            RequireEquals(manifest.root_local_motion_channels, 4, nameof(manifest.root_local_motion_channels));

            if (manifest.control_channels != 2 && manifest.control_channels != 4)
            {
                throw new BundleLoadException(
                    $"manifest.json: control_channels must be 2 or 4; got {manifest.control_channels}.");
            }

            if (manifest.phase_channels != 0 && manifest.phase_channels != 2)
            {
                throw new BundleLoadException(
                    $"manifest.json: phase_channels must be 0 or 2; got {manifest.phase_channels}.");
            }

            if (manifest.prompt_emb_channels < 0)
            {
                throw new BundleLoadException("manifest.json: prompt_emb_channels must be >= 0.");
            }

            if (manifest.context_frames < 1)
            {
                throw new BundleLoadException("manifest.json: context_frames must be >= 1.");
            }

            if (manifest.output_layout != "bone_delta|global_delta")
            {
                throw new BundleLoadException(
                    $"manifest.json: unexpected output_layout '{manifest.output_layout}'.");
            }

            if (manifest.coord_system != "Y-up right-handed")
            {
                throw new BundleLoadException(
                    $"manifest.json: unexpected coord_system '{manifest.coord_system}'.");
            }
        }

        private static void RequireEquals(int actual, int expected, string field)
        {
            if (actual != expected)
            {
                throw new BundleLoadException(
                    $"manifest.json: {field} must be {expected} (frozen contract); got {actual}.");
            }
        }

        private static NormStats LoadNormStats(string bundleDirectory)
        {
            var path = Path.Combine(bundleDirectory, NormStatsFileName);
            if (!File.Exists(path))
            {
                throw new BundleLoadException($"Bundle is missing '{NormStatsFileName}' at '{path}'.");
            }

            var json = File.ReadAllText(path);
            return NormStats.Parse(json);
        }

        /// <summary>
        /// Cross-checks between the manifest's declared dims and the stat
        /// buffer sizes actually parsed from norm_stats.json.
        /// </summary>
        private static void ValidateNormStats(Manifest manifest, NormStats stats)
        {
            var expectedBoneLen = manifest.num_bones * manifest.rotation_channels_per_bone;
            if (stats.BoneMean.Length != expectedBoneLen || stats.BoneStd.Length != expectedBoneLen)
            {
                throw new BundleLoadException(
                    $"norm_stats.json: state.bone_mean/std length must be {expectedBoneLen} " +
                    $"({manifest.num_bones}x{manifest.rotation_channels_per_bone}); " +
                    $"got mean={stats.BoneMean.Length}, std={stats.BoneStd.Length}.");
            }

            if (stats.GlobalMean.Length != manifest.root_local_motion_channels ||
                stats.GlobalStd.Length != manifest.root_local_motion_channels)
            {
                throw new BundleLoadException(
                    $"norm_stats.json: state.global_mean/std length must be " +
                    $"{manifest.root_local_motion_channels}; got mean={stats.GlobalMean.Length}, " +
                    $"std={stats.GlobalStd.Length}.");
            }

            if (stats.DeltaBoneMean.Length != expectedBoneLen || stats.DeltaBoneStd.Length != expectedBoneLen)
            {
                throw new BundleLoadException(
                    $"norm_stats.json: delta.bone_mean/std length must be {expectedBoneLen}; " +
                    $"got mean={stats.DeltaBoneMean.Length}, std={stats.DeltaBoneStd.Length}.");
            }

            if (stats.DeltaGlobalMean.Length != manifest.root_local_motion_channels ||
                stats.DeltaGlobalStd.Length != manifest.root_local_motion_channels)
            {
                throw new BundleLoadException(
                    $"norm_stats.json: delta.global_mean/std length must be " +
                    $"{manifest.root_local_motion_channels}; got mean={stats.DeltaGlobalMean.Length}, " +
                    $"std={stats.DeltaGlobalStd.Length}.");
            }

            // Control stats only ever cover vx,vz — aim is unit-norm, no stats (contract §3.2).
            const int controlNormChannels = 2;
            if (stats.ControlMean.Length != controlNormChannels || stats.ControlStd.Length != controlNormChannels)
            {
                throw new BundleLoadException(
                    $"norm_stats.json: control.mean/std length must be {controlNormChannels} (vx, vz only); " +
                    $"got mean={stats.ControlMean.Length}, std={stats.ControlStd.Length}.");
            }

            if (manifest.HasPrompt && stats.PromptNullEmb.Length != manifest.prompt_emb_channels)
            {
                throw new BundleLoadException(
                    $"norm_stats.json: prompt.null_emb length must equal manifest.prompt_emb_channels " +
                    $"({manifest.prompt_emb_channels}); got {stats.PromptNullEmb.Length}. " +
                    "A zero vector is NOT a valid substitute for a missing learned null embedding " +
                    "(inference_contract.md §4).");
            }
        }

        private static byte[] LoadOnnxBytes(string bundleDirectory)
        {
            var path = Path.Combine(bundleDirectory, OnnxFileName);
            if (!File.Exists(path))
            {
                throw new BundleLoadException($"Bundle is missing '{OnnxFileName}' at '{path}'.");
            }

            return File.ReadAllBytes(path);
        }

        private static IReadOnlyDictionary<string, ControlPresetData> LoadPresets(
            string bundleDirectory, Manifest manifest)
        {
            var presets = new Dictionary<string, ControlPresetData>();
            var presetsDir = Path.Combine(bundleDirectory, PresetsSubdirectory);
            if (!Directory.Exists(presetsDir))
            {
                return presets;
            }

            foreach (var file in Directory.GetFiles(presetsDir, "*.json"))
            {
                var json = File.ReadAllText(file);
                var preset = ControlPresetData.Parse(json);
                ValidatePreset(preset, manifest, file);
                presets[preset.name] = preset;
            }

            return presets;
        }

        private static void ValidatePreset(ControlPresetData preset, Manifest manifest, string sourcePath)
        {
            if (preset.promptEmb != null && preset.promptEmb.Length != manifest.prompt_emb_channels)
            {
                throw new BundleLoadException(
                    $"preset '{preset.name}' ({sourcePath}): prompt_emb length " +
                    $"({preset.promptEmb.Length}) does not match manifest.prompt_emb_channels " +
                    $"({manifest.prompt_emb_channels}).");
            }
        }
    }
}
