paths:
  dataset-root: "/Users/pazimor/dataset_preprocessed"
  # Optional: train only on selected preprocessed dataset folders.
  # Ex: ["KIT", "CMU", "ACCAD"]
  # dataset-folders: ["ACCAD", "BioMotionLab_NTroje", "BMLHandball", "BMLmovi", "CMU", "DFaust_67", "EKUT", "Eyes_Japan_Dataset", "HumanEva", "KIT", "MPI_HDM05", "MPI_Limits", "MPI_mosh", "SFU", "SSM_synced", "TotalCapture", "Transitions_mocap"]
  dataset-folders: ["ACCAD"] # for quick preview
  checkpoint-dir: ../../output/clip
  validation-indices: ../../output/clip/validation_indices.json
  # Network architecture is loaded from network.yaml
  network-config: "src/configs/network.yaml"

# ============================================
# Profile: Mac (32GB RAM, MPS GPU)
# ============================================
training:
  epochs: 5000
  device: mps
  max-length: 256
  model-name: xlm-roberta-base
  validation-split: 0.05
  early-stopping-patience: 100
  batch-size: 32
  gradient-accumulation: 1
  MM-memory-limit-gb: 20.0
  weight-decay: 0.01
  resume-checkpoint: ../../output/clip/best_model.pt
  
  # Learning Rate (constant)
  learning-rate: 0.00001

# ============================================
# Profile: Overfit
# ============================================
overfit:
  epochs: 1000
  device: mps
  max-length: 256
  model-name: xlm-roberta-base
  validation-split: 0.0
  early-stopping-patience: 100
  batch-size: 4
  gradient-accumulation: 1
  MM-memory-limit-gb: 20.0
  weight-decay: 0.0
  max-samples-per-epoch: 10000
  fixed-train-chunk: true
  overfit-samples: "10:12"
  disable-dropout: true
  resume-checkpoint: null

  # Learning Rate (constant)
  learning-rate: 0.00001
