"""Shared constant groups for AI-nimator."""

from .motion import (
    EPSILON,
    DEFAULT_FPS,
    SMPL22_BONES,
    SMPL24_BONES,
    LMF_JOINTS_SUBSET,
    LMF_POSE_EXPORT,
    SMPL22_NAME_ALIASES,
    SMPLH_CORE_INDEX_MAP,
)
from .rag import (
    RAG_STATE_DIRNAME,
    RAG_STATE_FILE,
    RAG_BATCH_INPUTS_DIR,
    RAG_BATCH_OUTPUTS_DIR,
    RAG_JSONL_MAX_BYTES,
    RAG_ONE_LINE_SOFT_LIMIT,
)
from .training import LOCAL_CLIP_RECORD_LIMIT

__all__ = [
    "EPSILON",
    "DEFAULT_FPS",
    "SMPL22_BONES",
    "SMPL24_BONES",
    "LMF_JOINTS_SUBSET",
    "LMF_POSE_EXPORT",
    "SMPL22_NAME_ALIASES",
    "SMPLH_CORE_INDEX_MAP",
    "RAG_STATE_DIRNAME",
    "RAG_STATE_FILE",
    "RAG_BATCH_INPUTS_DIR",
    "RAG_BATCH_OUTPUTS_DIR",
    "RAG_JSONL_MAX_BYTES",
    "RAG_ONE_LINE_SOFT_LIMIT",
    "LOCAL_CLIP_RECORD_LIMIT",
]
