"""Motion-related constant definitions."""

EPSILON = 1e-8
DEFAULT_FPS = 30.0

SMPL22_BONES = [
    "pelvis",
    "spine1",
    "spine2",
    "spine3",
    "neck",
    "head",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "toe_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "toe_r",
]

SMPL24_BONES = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hand",
    "right_hand",
]

LMF_JOINTS_SUBSET = [
    "spine1",
    "spine2",
    "spine3",
    "neck",
    "head",
    "upperarm_l",
    "lowerarm_l",
    "upperarm_r",
    "lowerarm_r",
    "thigh_l",
    "calf_l",
    "thigh_r",
    "calf_r",
    "foot_l",
    "foot_r",
]

LMF_POSE_EXPORT = {
    "spine_flex": ("spine3", 1),
    "spine_side": ("spine3", 0),
    "head_pitch": ("head", 1),
    "head_yaw": ("head", 2),
    "L_shoulder_flex": ("upperarm_l", 1),
    "L_abduction": ("upperarm_l", 0),
    "L_elbow_flex": ("lowerarm_l", 1),
    "R_shoulder_flex": ("upperarm_r", 1),
    "R_abduction": ("upperarm_r", 0),
    "R_elbow_flex": ("lowerarm_r", 1),
    "L_hip_flex": ("thigh_l", 1),
    "L_knee_flex": ("calf_l", 1),
    "L_ankle_flex": ("foot_l", 1),
    "R_hip_flex": ("thigh_r", 1),
    "R_knee_flex": ("calf_r", 1),
    "R_ankle_flex": ("foot_r", 1),
}


SMPL22_NAME_ALIASES = {
    "pelvis": ["pelvis", "hips", "root", "hip"],
    "spine1": ["spine1", "spine_01", "spine"],
    "spine2": ["spine2", "spine_02"],
    "spine3": ["spine3", "spine_03", "chest"],
    "neck": ["neck", "neck_01"],
    "head": ["head", "head_01"],
    "clavicle_l": ["clavicle_l", "leftshoulder", "clavicle_left", "shoulder_l", "left_collar"],
    "upperarm_l": ["upperarm_l", "leftarm", "upperarm_left", "arm_l", "left_shoulder"],
    "lowerarm_l": ["lowerarm_l", "leftforearm", "forearm_l", "left_elbow"],
    "hand_l": ["hand_l", "lefthand", "hand_left", "left_wrist", "left_hand"],
    "clavicle_r": ["clavicle_r", "rightshoulder", "clavicle_right", "shoulder_r", "right_collar"],
    "upperarm_r": ["upperarm_r", "rightarm", "upperarm_right", "arm_r", "right_shoulder"],
    "lowerarm_r": ["lowerarm_r", "rightforearm", "forearm_r", "right_elbow"],
    "hand_r": ["hand_r", "righthand", "hand_right", "right_wrist", "right_hand"],
    "thigh_l": ["thigh_l", "leftupleg", "upleg_l", "left_hip"],
    "calf_l": ["calf_l", "leftleg", "leg_l", "left_knee"],
    "foot_l": ["foot_l", "leftfoot", "foot_l", "left_ankle"],
    "toe_l": ["toe_l", "lefttoe", "lefttoebase", "toe_end_l", "toe1_l", "left_foot"],
    "thigh_r": ["thigh_r", "rightupleg", "upleg_r", "right_hip"],
    "calf_r": ["calf_r", "rightleg", "leg_r", "right_knee"],
    "foot_r": ["foot_r", "rightfoot", "foot_r", "right_ankle"],
    "toe_r": ["toe_r", "righttoe", "righttoebase", "toe_end_r", "toe1_r", "right_foot"],
}


SMPLH_CORE_INDEX_MAP = {
    "pelvis": 0,
    "thigh_l": 1,
    "thigh_r": 2,
    "spine1": 3,
    "calf_l": 4,
    "calf_r": 5,
    "spine2": 6,
    "foot_l": 7,
    "foot_r": 8,
    "spine3": 9,
    "toe_l": 10,
    "toe_r": 11,
    "neck": 12,
    "clavicle_l": 13,
    "clavicle_r": 14,
    "head": 15,
    "upperarm_l": 16,
    "upperarm_r": 17,
    "lowerarm_l": 18,
    "lowerarm_r": 19,
    "hand_l": 20,
    "hand_r": 21,
}
