"""Constants used for the RAG OpenAI tooling."""

STATE_DIRNAME = ".rag_openai"
STATE_FILE = "state.json"
BATCH_INPUTS_DIR = "batch_inputs"
BATCH_OUTPUTS_DIR = "batch_outputs"
JSONL_MAX_BYTES = 180 * 1024 * 1024
ONE_LINE_SOFT_LIMIT = 900_000

RAG_STATE_DIRNAME = STATE_DIRNAME
RAG_STATE_FILE = STATE_FILE
RAG_BATCH_INPUTS_DIR = BATCH_INPUTS_DIR
RAG_BATCH_OUTPUTS_DIR = BATCH_OUTPUTS_DIR
RAG_JSONL_MAX_BYTES = JSONL_MAX_BYTES
RAG_ONE_LINE_SOFT_LIMIT = ONE_LINE_SOFT_LIMIT
